### ISSUE TITLE
Plugin description is outdated

### ISSUE THREAD

**Issue by Hinni** [plexinc-plugins/Schweizer-Fernsehen.bundle#11]
The description of the plugin in the channel directory is not valid anymore. How to change this? Do I have to request a change at https://www.transifex.com/ or how to chnage this description?

**Comment by sander1** [comment]
Hi @Hinni! I have to change this manually. Can you give me a new description? I'll update it asap.
Thanks!

**Comment by Hinni** [comment]
Please use this text for the description:

Dieses Plug-in bietet den Zugriff auf die Podcasts des Schweizer Fernsehen. Verfügbar sind die meisten deutschen Eigenproduktionen.

thank you for your time @sander1 !

**Comment by sander1** [comment]
Thank you! The description has been updated!
