### ISSUE TITLE
SRF Plugin findet keine Episoden

### ISSUE THREAD

**Issue by blub-spamwc** [plexinc-plugins/Schweizer-Fernsehen.bundle#9]
Hi!

Habe gerade die neuste Version des Plex Plugins für SRF installiert.
Die einzelnen Kanäle (10 vor 10, 1 gegen 100 etc.) werden aufgelistet.
Wenn man nun aber eines anklickt erscheint nur die Meldung "This show has no episodes available"
Gibts hier ein Update? Mache ich evtl. was falsch?

**Comment by cansik** [comment]
Habe das gleiche Problem. Wir wohl ein Problem beim parsen des HTML's sein. Ein API anzusprechen würde wohl einige Probleme lösen!

**Comment by Hinni** [comment]
Beim nächsten Update der Server Version sollte das Plugin wieder funktionieren :-)
